#
# MY_PIPELINE config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content
custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ' of sequenced data. Note that in the context of paired-end data, the number pairs are reported (as reads). Low **NSC** and **RSC** values can be due to failed and poor quality ChIP, low read sequence quality and hence lots of mismappings, shallow sequencing depth or a combination of these. Also, datasets with few binding sites (< 200) which could be due to biological reasons (i.e. a factor that truly binds only a few sites in a particular tissue type) would output low NSC and RSC scores.'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            id: 'stats'
            title: 'General Statistics'
            save_file: true
            col1_header: 'Sample_ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
              format: '{:.0f}'
              placement: 1000
            Number_of_reads:
              title: 'Total Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              placement: 2000
            Fragment_length:
              title: 'Fragment Length'
              scale: 'YlGnGn'
              format: '{:,.0f}'
              placement: 3000
            Number_of_aligned_reads:
              title: 'Aligned Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 3000
            Percent_of_aligned_reads:
              title: 'Aligned Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 4000
            Number_of_uniquely_mapped_reads:
              title: 'Unique Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 5000
            Percent_of_uniquely_mapped_reads:
              title: 'Unique Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 6000
            Number_of_multiple_mapped_reads:
              title: 'Multiple reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 7000
            Percent_of_multiple_mapped_reads:
              title: 'Multiple reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 8000
            Number_of_duplicates:
              title: 'Duplicates'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 9000
            Percent_of_duplicates:
              title: 'Duplicates (%)'
              min: 0
              max: 100
              scale: 'RdYlVBu'
              format: '{:,.1f}'
              suffix: '%'
              placement: 10000
            Normalized_strand_correlation:
              title: 'NSC'
              min: 0.8
              max: 3
              scale: 'RdYlGn'
              format: '{:,.2f}'
              placement: 11000
            Relative_strand_correlation:
              title: 'RSC'
              min: 0
              max: 2
              scale: 'RdYlGn'
              format: '{:,.2f}'
              placement: 12000
            Fraction_of_reads_in_peaks:
              min: 0
              max: 1
              title: 'FRiP'
              scale: 'RdYlGn'
              format: '{:,.2f}'
              placement: 13000

   splike:
        file_format: 'csv'
        section_name: 'Spike-in'
        description: 'statistics of spike-in alignment data."
        plot_type: 'bargraph'
        pconfig:
            title: 'Spikes'
            id: 'spikes'
            scale: 'Set2'    

   my_mapping_plot:
        file_format: 'csv'
        section_name: 'Mapping'
        description: 'statistics on aligned data. Number of unique and multiple mapped reads, as well unmapped reads are reported.'
        plot_type: 'bargraph'
        pconfig:
            title: 'Reads Alignment on Reference Genome'
            id: 'mapping'
            scale: 'Set2'    

sp:
  my_stats:
      fn: '*.stats'
  spikes:
      fn: '*bamcomp.log'
  bwa_logs:
      fn: '*bwa.log'

table_cond_formatting_rules:
    Percent_of_aligned_reads:
        pass:
          - gt: 80
        warn:
          - lt: 80
        fail:
          - lt: 50
    Percentage_of_duplicates:
        pass:
          - lt: 25
        warn:
          - gt: 25
        fail:
          - gt: 50
    Normalized_strand_correlation:
        pass:
          - gt: 1.05
        warn:
          - lt: 1.05
        fail:
          - lt: 1
    Relative_strand_correlation:
        pass:
          - gt: 0.8
        warn:
          - lt: 0.8
        fail:
          - lt: 0.3
    Fraction_of_reads_in_peaks:
        pass:
          - gt: 0.01
        fail:
          - lt: 0.01


###############################
## Modules 

module_order:
   - fastqc
   - bowtie2
   - star
   - picard
   - preseq
   - phantompeakqualtools 
   - macs2
   - deeptools
   - homer

report_section_order:
  strand_shift_correlation:
      order: -1200
  peak_count:
      order: -1300
  peak_annotation:
      order: -1500
  deeptools_correlation:
      order: -1600
  deeptools_fingerprint:
      order: -1700
  read_distribution_profile_plot:
      order: -1900
  Chip-seq_pipeline_software_versions:
      order: -2000
  summary:
      order: -2100

#############################
## Removed plots
remove_sections :
  - fastqc_sequence_counts
  - fastqc_per_sequence_quality_scores
  - fastqc_overrepresented_sequences
  - fastqc_status_checks
  - plotFingerprint

fn_ignore_files:
  - '*_spp_nsc_*'
  - '*_spp_rsc_*'
  - '*FRiP*'
  - '*count_mqc*'
  - '*_sorted*'

#############################
## Display

plots_force_interactive: True
